### ISSUE TITLE
CYF Blocks (Step 5): Clarify CYF Blocks Step Instructions and Expected Output

### ISSUE THREAD

**Issue by AmyCYF** [CodeYourFuture/curriculum#1056]
**Description:**
There is significant confusion among participants regarding what is expected for each step in CYF Blocks. Participants are unsure about the correct output and instructions, making it difficult to assess the steps consistently. Volunteers also struggle to understand which step a participant is attempting when reviewing the code.

**Acceptance Criteria:**

- [ ] Clearly define and standardise the expected output for each CYF Block step.
- [ ] Include examples of correct output for each step.
- [ ] Ensure that the submission includes a reference to the step number in the CYF Blocks dashboard?
- [ ] Volunteers are able to identify the step and its expected outcome without needing to cross-reference multiple sources.

CJ/Peter - ITD Syllabus

**Comment by mjpeet** [comment]
checked the "old" task description on the link (google doc), personally i find that more "supportable" by volunteers if there are questions (from trainees)

**Comment by illicitonion** [comment]
One thing I'll note about CYF Blocks - we had originally hoped that it would help our trainees with things like "breaking down problems" and "understanding control flow" and similar before being exposed to JS. AFAIK we have not observed this in practice - I've never seen a trainee link what they did in CYF Blocks with what they are learning in JS.

One thing that _is_ very cool about CYF Blocks though is that it can allow you to make interactive elements of your existing HTML page without learning _any_ JS. Fundamentals used to do this (having people add e.g. an interactive image carousel to their website), and this is a genuinely very impressive and cool thing to be able to do without writing any code. I'm not sure if we've preserved that in the move from Fundamentals to ITD...

**Comment by cjyuan** [comment]
The feedbacks I saw on CYF were mainly "instructions are not clear". So I will focus on that.

Here are the changes I have in mind:
**Objective of exercises**:  To help participants understand how to use the blocks (especially HTML and Array blocks)
To achieve this objective, I am planning to introduce block examples to explain how to use the blocks (one example for one block), then ask the participants to practice using the blocks in exercises.
To implement this suggested changes, we will need to prepare the examples and rewrite the instructions in the current exercises.

**Objective of projects**: To encourage participants to solve a larger problem.
Image Carousel is one of the fun one.

I think we can make some changes to some of the projects:
- Some of them might be "too easy" (e.g., selecting a random facilitator) 
- Rewrite the spec to "encourage" them to use loops or functions. 
  - (For example, in "List of links", ask them to generate a list from an array of 10 links (or from an array of variable number of links) so that they can't easily copy-paste their blocks 2 times to avoid using loop. 
- I don't know if any of them tried Story Book. I think we can give them some hints here.

**Comment by cjyuan** [comment]
You can preview my proposed changes via this repo: 
https://github.com/cjyuan/fundamentals-blockly

You can run it from a Live Server in VSCode. There is no server-side code.
Load `index-examples.html` to see how the examples look like (Only 1 example at the moment).
Load `index.html` to see the exercises (Only the first exercise, "Change text", is modified).

You can help fixing my English later. 

Let me know what you think before I make more changes.

**Comment by SallyMcGrath** [comment]
@cjyuan can you open it as a PR and add us as reviewers? Just because there are so many tickets and this can't get lost

**Comment by SallyMcGrath** [comment]
Also did you come to a conclusion about CYF Blocks vs my old Build a Personal Home Page?

**Comment by cjyuan** [comment]
Personal Homepage (Useful to strengthen HTML and CSS skills, just might be too similar to the Hometown Homepage in step 4)

CYF Blocks (Skills learned in this step are less useful in later module, but it is something different, fun but also intimidating)

I prefer the Personal Homepage, with additional elements to distinguish it from the task in Step 4. But at the end, it will depend on our goal.

**Comment by SallyMcGrath** [comment]
What do you think about Scrimba? Do we keep it or swap it for #1103 ?
