### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by ifiok-akpan** [CodeYourFuture/curriculum#1231]
**Describe the bug**
Contributing.md not opening. 

The bug prevent users from seeing the contributing guidelines.

**What is wrong with this content?**
<img width="1335" alt="Screenshot 2024-12-06 at 1 27 34 PM" src="https://github.com/user-attachments/assets/56dffe08-4616-4dfa-99f9-8bc1452cfe7a">

**How could this be fixed?**
Troubleshooting 404 error

**Link to content**
https://github.com/CodeYourFuture/curriculum/blob/main/contributing.md

**Comment by illicitonion** [comment]
Thanks for the report!

Where did you find this link?

The problem is the case of the filename - the file is actually called CONTRIBUTING.md not contributing.md - https://github.com/CodeYourFuture/curriculum/blob/main/CONTRIBUTING.md works fine for me.

Can you share where you found this link which is written in the wrong case?

Thanks!

**Comment by ifiok-akpan** [comment]
On the Readme.md file. the markdown link showed on the image below. "how to contribute"

<img width="883" alt="Screenshot 2024-12-06 at 6 20 28 PM" src="https://github.com/user-attachments/assets/6bc3aa21-1377-4d79-8051-634d8424a5d2">

**Comment by ifiok-akpan** [comment]
Thanks. I will follow up and test again.
