### ISSUE TITLE
Issues in module repository backlog do not appear on the curriculum site's backlog

### ISSUE THREAD

**Issue by JayMayer** [CodeYourFuture/curriculum#333]
**Describe the bug**

GitHub issues from module repos are not appearing on the curriculum site's backlog.

**What is wrong with this content?**

Trainees and volunteers are unable to get a complete picture of the backlog from the curriculum site.

**How could this be fixed?**

Ensure that the backlog displayed on the curriculum site is the same as the backlog in the module repository.

**Link to content**

Example using HTML-CSS Sprint 1 (note the content is different)
- [Curriculum Site Backlog](https://curriculum.codeyourfuture.io/html-css/sprints/1/backlog/)
- [Module Repo Backlog](https://github.com/orgs/CodeYourFuture/projects/87/views/4?filterQuery=-status%3A%22%E2%9C%85+Done%22+week%3A%22Week+1%22)

**Additional context**

Not all issues are affected, some are displayed.

The bug has only been observed recently, in the past all issues have been displayed.

**Who else might need to know about this?**

@AltomHussain @SallyMcGrath

**Comment by SallyMcGrath** [comment]
OK walking through this. I've spun up the repo and running it on local. 

On 

http://localhost:1313/html-css/sprints/1/backlog/ = 2 issues showing of 
http://localhost:1313/html-css/sprints/3/backlog/ = 3
http://localhost:1313/html-css/sprints/5/backlog/ = 5

the issues api being passed to the issues partial on all these views is https://api.github.com/repos/CodeYourFuture/Module-HTML-CSS/issues?per_page=100 and all the issues show on this view

I move into the partial. Inside the issues range, the first piece of logic is filtering the issues to show if a label matches the parameter passed in. I comment this out, to see if it shows all the issues. I get a giant error

`render of "page" failed: [1;36m"/Users/me/CYF/Repos/curriculum/layouts/_default/backlog.html:9:7"[0m: execute of template failed at <partial "issues.html" .>: error calling partial: [1;36m"/Users/me/CYF/Repos/curriculum/layouts/partials/issues.html:41:48"[0m: execute of template failed at <markdownify>: error calling markdownify: [1;36m"/Users/me/CYF/Repos/curriculum/content/_index.md:1:1"[0m: [1;36m"/Users/me/CYF/Repos/curriculum/layouts/_default/_markup/render-image.html:33:19"[0m: execute of template failed at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc00ffe95f0 0xc000cacdc0} render of "page" failed: &{0xc0106be8f0 0xc000ca6c80}  render: failed to render pages: &{0xc00f901c70 0xc000ca2f00}` 

Interesting! This suggests to me it's to do with a piece of content on an issue in this module. Before I go chase that down, I'll check issues from another module, to see if it is also short...

Looks like http://localhost:1313/js1/sprints/1/backlog/ matches https://github.com/orgs/CodeYourFuture/projects/91/views/2 with nothing missing. I'll check more sprints... yes they all match. So for now I'll guess it's to do with the HTML module in particular and go look at what is triggering the render image hook. 

I search the api for `img` and find https://github.com/CodeYourFuture/Module-HTML-CSS/pull/168 which contains this code

`<img width="1512" alt="Screenshot 2023-10-20 at 14 21 09" src="https://github.com/CodeYourFuture/Module-HTML-CSS/assets/126393077/6d630a24-38c7-42e1-b0da-aece5c8179bf">
![Uploading Screenshot 2023-10-20 at 14.21.17.png…]()`

This is an html image tag followed by a markdown image tag with no source. It seems like we've discovered that our render hook needs better error handling to parse and skip broken code. Now I want to understand which part is breaking it. As I have edit access to this PR, I will just edit out the empty markdown and see what happens. Hrm - no more error, but when I return the filtering, the issues list is still cutting off at 2. This makes me think there are likely two problems:

1. error handling on render_image
2. issues cutting off. 

Looking again at the filter cut off, when I remove the filters, I get 100 issues. Given that this error only happened recently, and we have two classes going through this module for the first time, I hypothesise that the issues have been pushed off the API call. Given that the list is only going to get longer, it seems like I need to find an API call that preselects issues out of the issues API, unless I want to page through to find all the possible issues, which seems like it could start to get slow.  Hrm.

I remember that we didn't use Milestones because you can't copy the id across repos -- it's unique to the repo so it makes cloning complicated. But maybe I can group the issues I want with a milestone and get that instead. I go to Module-HTML-CSS and create a test milestone for Week 1 and add the Week 1 issues to it. Then I look up the milestones API... hm, no that doesn't seem useful. My issues API call can probably be improved more easily. I suspect we didn't add the label filter to the API call because it has to match a label exactly and our templating filter allows partial match, but given we've now hit this problem, a first solution is to update the API call to filter on the exact label.

Actions (in the morning)

1. move the filtering from the loop to the api call in issues.html and update the backlog_filter param to match the label exactly
2. improve error handling of invalid image code in render_image
