### ISSUE TITLE
Issue embedding: Lists get lost in markdown interpretation

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#62]
**Describe the bug**

On https://cyf-curriculum.netlify.app/fundamentals/sprints/1/backlog/ in the Code.org backlog item, in the GitHub issue the list of lessons to do is nicely newline-separated:

<img width="825" alt="Screenshot 2023-06-11 at 13 53 57" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/5d8e91d7-ad37-4e67-ba5e-470b1eb929c5">

When embedded in Hugo, it isn't:

<img width="697" alt="Screenshot 2023-06-11 at 13 54 20" src="https://github.com/CodeYourFuture/curriculum/assets/1131704/be8e8f57-42ea-4718-8908-b6f1740b9d2a">

I'm not sure what wizardry GitHub issue are doing here, because in markdown I _would_ expect these to be rendered as a single run-on line, but it appears GitHub issues does something smart to avoid this - we should try to emulate it.

In the short-term, we could edit the issue to have a bulleted list, which should make them appear correctly, but in general I suspect we'll hit this issue again in the future, so we should consider a structural fix.

**Comment by SallyMcGrath** [comment]
That is interesting. It's sort of the eternal question isn't it? Should we fail incorrect markup or fix it for them. And in which case, what assumptions do we make? 

In my experience (oh parsers!!) it's easier to fail the markup when the users are power users. 

Github is parsing and adding a br, so it's layout without meaning - in this case we probably always want to have a list as it will give a traversible countable sequence of lessons instead of one run on blob of text (to screenreaders etc). That being said, maybe we also want hard wrap. 

I read https://spec.commonmark.org/0.30/#soft-line-breaks and it suggested the renderer can choose to break on this character, so then I looked at the hugo markdown config options and sure enough they have them toggled off

https://gohugo.io/getting-started/configuration-markup/

I will toggle them on

**Comment by 40thieves** [comment]
> it's easier to fail the markup when the users are power users.

Factoring in PD folks here, I think we should probably switch on that hard wrap option - it is one of those things that I've found breaks people's expectations of what markdown produces.

So I'm in favour of merging #69.
