### ISSUE TITLE
Create backlog for new users of our curriculum

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/curriculum#623]
## Acceptance criteria 📝 

- [x] Max 3 backlog tasks for new users of the curriculum 

## Ideas 💡 

- Check you're part of the right Slack channel
- Discuss something with one of the trainees - may be reference pedagogic vocabulary
 
### Owner
@Dedekind561 

### Stakeholder
@SallyMcGrath 

### Approver
@CodeYourFuture/global-syllabus

**Comment by kfklein15** [comment]
Should one be something like: Understand how the flipped classroom works OR Understand how the be a facilitator, not a teacher

**Comment by Dedekind561** [comment]
I would say that Understand how flipped classroom works is more like a top level objective for the entire module. To fully understand flipped classroom new volunteers will have also have to understand the rhythm of the week and a bunch of other concepts which are threaded throughout this module. So I think this backlog needs to be more concrete actions with more well-defined learning objectives: https://curriculum.codeyourfuture.io/how-our-curriculum-works/sprints/self-educate/backlog/

**Comment by kfklein15** [comment]
@Dedekind561 , I read the new [Module](https://curriculum.codeyourfuture.io/how-our-curriculum-works/) and it is looking fantastic! Really loved the self-education one.

Question:
- Did you review the language on the [prep](https://curriculum.codeyourfuture.io/how-our-curriculum-works/prep/) tab of it for English level B1 users? Because we want our trainees to understand it too.
