### ISSUE TITLE
Kamino Clone button doesn't work

### ISSUE THREAD

**Issue by pseudopilot** [CodeYourFuture/curriculum#785]
**Describe the bug**

Kamino Clone button is not cloning the issues.
But I can't be 100% sure that it's not just some my local problem.

https://github.com/CodeYourFuture/curriculum/assets/40791399/849ff15f-75ee-47e5-aaab-20e04fa2d8f0

**What is wrong with this content?**

**How could this be fixed?**

If the problem is confirmed by someone else, we can raise an issue in the repository https://github.com/gatewayapps/kamino.

**Link to content**

**Additional context**

**Who else might need to know about this?**

**Comment by moneyinthesky** [comment]
Hey @pseudopilot, I had a similar issue in the past.
I was able to resolve it by using a fine-grained access token instead of a classic token. I also needed to ensure I had these permissions set:
![Image](https://github.com/CodeYourFuture/curriculum/assets/19252665/4a86f4c1-3c6c-4e3e-afc8-f0f66df15a9c)

**Comment by JayMayer** [comment]
This is relevant to #786 as well. I've left [some thoughts](https://github.com/CodeYourFuture/curriculum/issues/786#issuecomment-2218568756) on dropping Kamino and use the "Clone" buttons exclusively.
