### ISSUE TITLE
How Our Curriculum Works success page is empty

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#915]
https://programming.codeyourfuture.io/how-our-curriculum-works/success/ contains no learning objectives

https://programming.codeyourfuture.io/how-our-curriculum-works/sprints/self-evaluate/prep/ directs people to find this page and understand it.

It should probably not be empty.

Maybe we should collate the per-sprint LOs into this page? Or maybe we just need to come up with some module-level LOs for this module.

cc @Dedekind561 @SallyMcGrath

**Comment by SallyMcGrath** [comment]
https://common.codeyourfuture.io/common-theme/pages/success/#module-view

As in our convo recording here -- it's empty by design - we must add them for the module. But we do want an error if there's nothing added as that's not a complete module and shouldn't be published.

I will add some starters now, and then hand over to you. I see the draft error and presume you are on the other part
