### ISSUE TITLE
How Our Curriculum Works is inconsistently copied across multiple sites

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#922]
`{itp,sdc,tracks}/content/how-our-curriculum-works/success/index.md` currently contain no learning objectives, so I'm adding them. But I don't want to have to add (and maintain) the same LOs across each version. I was about to symlink across between them, but it feels like ideally there would be one common version that all three sites reference, rather than picking one to be canonical and having the others reference it.

Similarly, `org-cyf-itp/content/how-our-curriculum-works/sprints/self-educate/prep/index.md` is currently missing the `module/how-our-curriculum-works/dialogue` block between No Lectures and Importance of Prep - the other two sites have this. Ideally these would be structurally shared as the same, rather than copied and kept in sync.

@SallyMcGrath What's the best way to achieve this?

**Comment by SallyMcGrath** [comment]
So, if we want them to be a single module, maintained centrally, we can do that. We can register them as a module and mount them in, like guides. 

@Dedekind561 didn't want this, I think because he was imagining each course would diverge significantly over time in its setup. However, you can merge a mounted module with local content I think? :/ Don't quote me. 

If you would prefer to maintain one module, here's how you would do that

1. make a new directory called how-our-curriculum-works (or what you want) and touch a hugo.toml 
1. move the how our curriculum works module into this and rename it "content"
1. register this as a hugo module by running hugo mod init github.com/CodeYourFuture/curriculum/YOUR_DIR
1. now edit your hugo.toml with the following:

```
title = "How our curriculum works"
description="ADD SMTH"
baseURL = "https://curriculum.codeyourfuture.io/"

[module]
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-theme"
``` 

Now everywhere you want the module, mount it in that hugo.toml like this

```
  [[module.imports]]
    path = "github.com/CodeYourFuture/curriculum/org-cyf-DIRNAME" 
    [[module.imports.mounts]]
      source = "content"
      target = "content/DIRNAME"
```

Don't be tempted to add it to org-cyf-theme -- nothing in there should create pages.

**Comment by SallyMcGrath** [comment]
I think combine it for now.

It's really easy to diverge later
