### ISSUE TITLE
Retro block video uses Jamboard

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#942]
https://www.youtube.com/watch?v=dY6yFsgLrBA tells people to use a Jamboard to run a retro.

Jamboard is going away in 2 weeks, RIP.

We should replace this.

**Comment by SallyMcGrath** [comment]
- [x] I have [made a FigJam](https://www.figma.com/board/otHBufZ3jGm9S7QPxeuXYV/Retro-Board-CYF?node-id=0-1&t=UEnj1KfKssCK1hYl-1) because we have these free pro accounts with Figma so we won't hit the limits on Miro and accidentally disable someone's vital board
- [x] I have added a few other people as editors eg @illicitonion @moneyinthesky @kfklein15 etc and made it public edit with a password
- [ ] I have changed the video I found in wow2 to say figjam, re-rexported and [uploaded it to Youtube](https://www.youtube.com/watch?v=TeKHx6GY3Zw)
- [ ] I have edited the link in the common retro block
- [ ] I have searched in common to find any other references to this video and found none
- [ ] I have put a note in Slack saying where the board is and how to access it
