### ISSUE TITLE
Front End Practice prep work has 0 maximum time

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#952]
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/87 is currently allocated 0 hours.

There is currently no prep work this sprint, and the existing backlog is about 7 hours, so in theory there's currently about 13 hours that could be allocated to it. Though I suspect a bunch of SQL-shaped content may find itself into this sprint?

**Comment by moneyinthesky** [comment]
Hey @illicitonion, I was thinking the 0 hour allocation may have been intentional because it's a stretch exercise, as maybe we didn't want this to count towards the 20 hour limit?
And yes, there's some DB content coming into Sprint 3 of this module so that will take up some of the time (although probably not all of it!) 😄

**Comment by SallyMcGrath** [comment]
Indeed, Stretch work is not assigned times because it doesn't count towards the total time allotted, which is 20 hours INCLUDING the prep work.

There used to be a ticket on here with the prep work on it. Not sure what happened to that. In any case, I have added a time total on the prep view itself to try to help us with this. #985

**Comment by illicitonion** [comment]
Hmm... I think this is quite an unclear thing to read:

> ### Maximum time in hours
> 
> 0

How would you feel if we reworded this instead to:

> ### Maximum time in hours
> 
> This is a stretch assignment - you are not required to spend any time on this, but we strongly recommend you spend any extra time you have on this, as it will help you to become a developer.

**Comment by SallyMcGrath** [comment]
I'd feel fine about this, but the field that sums the total hours on the planner is a number not text.

If they don't need to match then this is ok by me.

**Comment by illicitonion** [comment]
I'm going to make the edit - we can worry about the sum-er when we write it :)
