### ISSUE TITLE
Percentage change exercise says there's an error and there isn't

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#967]
In this coursework: https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/blob/fd47e0c62f0a6b7ac2ee09bf7061f06282e7f297/Sprint-1/interpret/percentage-change.js#L16

The instruction is: "Run the code and identify the line where the error is coming from"

But this code does not produce an error.

I don't know what error was intended, but we should I suppose add one. @Dedekind561 I think you made this exercise originally?

**Comment by SallyMcGrath** [comment]
I do not know, because I didn't write it, but my bet is that this line

https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/blob/fd47e0c62f0a6b7ac2ee09bf7061f06282e7f297/Sprint-1/interpret/percentage-change.js#L5

is meant to be `priceAfterOneYear = Number(priceAfterOneYear);` and the error is NaN and an autocomplete chomped it

**Comment by illicitonion** [comment]
I've filed https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/pull/37 introducing an error.

I believe it was intended to be a syntax-ish error, from what's in the prep, and I don't think we've introduced the concept of `NaN` yet...
