### ISSUE TITLE
Check module success criteria inconsistency

### ISSUE THREAD

**Issue by illicitonion** [CodeYourFuture/curriculum#969]
In User Focused Data, https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/45 is assigned in sprint 3.

In Structuring and Testing Data, https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/3 is assigned in sprint 1.

It feels like these should be consistently assigned, probably to the end of the sprint?

See also https://github.com/CodeYourFuture/curriculum/issues/940

**Comment by moneyinthesky** [comment]
I left a comment on https://github.com/CodeYourFuture/curriculum/issues/940 - but based on my interpretation, I'm thinking making this consistent by moving to the beginning of each module makes sense?

**Comment by pseudopilot** [comment]
I'm leaving my comments here too because I encountered this inconsistency when reviewing another topic. I did some research and fixed 2 broken links.


**Module-User-Focused-Data**
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/45
It's tagged for both **Sprint 1** and **Sprint 3**

**Module-Structuring-and-Testing-Data**
https://github.com/CodeYourFuture/Module-Structuring-and-Testing-Data/issues/27
It's tagged only for **Sprint 1**

**Module-Data-Groups**
https://github.com/CodeYourFuture/Module-Data-Groups/issues/6
It's tagged only for **Sprint 1**
❗ The link to the coursework was broken. I updated it with the working one: https://programming.codeyourfuture.io/data-groups/success/

**Module-Data-Flows**
https://github.com/CodeYourFuture/Module-Data-Flows/issues/5
It's tagged for both **Sprint 1** and **Sprint 3**
❗ The link to the coursework was broken. I updated it with the working one: https://programming.codeyourfuture.io/data-flows/success/

**Comment by SallyMcGrath** [comment]
We think this is sorted? @moneyinthesky what do you think?
