### ISSUE TITLE
Google Doc and Slides Class code not found

### ISSUE THREAD

**Issue by fcaroline2020** [CodeYourFuture/curriculum#979]
**Describe the bug**

Backlog Task: `[PD] Learn how to use Google Doc and Slides #69`

says to use a class code but when I tried entering it I got `We couldn't find a class with that code.`

**What is wrong with this content?**

Class code not found
<img width="774" alt="Screenshot 2024-09-21 at 10 09 18 AM" src="https://github.com/user-attachments/assets/9637d46f-fc0f-4aa9-8af2-f641f85b4cd2">

**How could this be fixed?**
Correct class code

**Link to content**
https://github.com/CodeYourFuture/Module-User-Focused-Data/issues/69

**Additional context**

**Who else might need to know about this?**

**Comment by SallyMcGrath** [comment]
This is a PD task (I merely own the account that bulk created these issues with https://www.npmjs.com/package/batch-issue-cloner?activeTab=code)

However PD are away until October 5 so I suggest that instead of creating a new class, we probably don't actually want a class, just the lessons?

So it's the same resource as they use in ITD to do spreadsheets. I've found the referenced course and updated the ticket with a direct link.
